"""care facility contact request message field

Revision ID: 527d39e218d1
Revises: f6ef02ab0e86
Create Date: 2025-03-07 18:37:34.657087

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '527d39e218d1'
down_revision = 'f6ef02ab0e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carefacilitycontactrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carefacilitycontactrequest', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###
