"""create care facilities table

Revision ID: 080f5913eb0a
Revises: 
Create Date: 2025-03-06 14:05:59.702444

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '080f5913eb0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carefacility',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('has_stationary_care', sa.Boolean(), nullable=False),
    sa.Column('has_day_care', sa.Boolean(), nullable=False),
    sa.Column('has_ambulatory_care', sa.Boolean(), nullable=False),
    sa.Column('from_zip_code', sa.Integer(), nullable=False),
    sa.Column('to_zip_code', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('available_capacity', sa.Boolean(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_carefacility_zip_code'), 'carefacility', ['zip_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carefacility_zip_code'), table_name='carefacility')
    op.drop_index(op.f('ix_carefacility_has_stationary_care'), table_name='carefacility')
    op.drop_index(op.f('ix_carefacility_has_day_care'), table_name='carefacility')
    op.drop_index(op.f('ix_carefacility_has_ambulatory_care'), table_name='carefacility')
    op.drop_index(op.f('ix_carefacility_available_capacity'), table_name='carefacility')
    op.drop_table('carefacility')
    # ### end Alembic commands ###
