"""care facility image url

Revision ID: c0e527e36f67
Revises: 7f76c2701ea6
Create Date: 2025-03-06 21:29:48.490818

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c0e527e36f67'
down_revision = '7f76c2701ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carefacility', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carefacility', 'image_url')
    # ### end Alembic commands ###
